import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>

        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs,huntingcoder blog, hunting coder"
        />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.imagewrapper}>
          <img
            className={styles.myImg}
            src="/Homeimg.avif"
            width={237}
            height={158}
            alt="hunting coder"
          />
        </div>

        <h1 className={styles.title}>
          <span className="mySpan dummy">&lt;Hunting Coder/&gt;</span>
        </h1>
        <div className="blogs">
          <div>
            <h2 className={styles.h2}>Latest Blogs</h2>
            <h3 className={styles.h3}>How to learn JavaScript</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web Lorem,
              ipsum dolor.
            </p>

            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web Lorem,
              ipsum dolor.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div>
            <h3 className={styles.h3}>How to learn JavaScript</h3>
            <p className={styles.p}>
              JavaScript is the language used to design logic for the web Lorem,
              ipsum dolor.
            </p>
            <button className={styles.btn}>Read More</button>
          </div>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
